import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.box}>
          <h1 className={styles.title}>Upload your image</h1>
          <span className={styles.description}>File should be Jpeg, Png,...</span>
          <div className={styles.upload_box}>
            <label className={styles.upload_label}>Drag & Drop your image here </label>
            <input className={styles.upload_box_input} type="file" id="file" name="file" />
          </div>
          <span className={styles.span}>or</span>
          <input className={styles.box_input} type="file" id="file" name="file" />
        </div>
      </main>
    </div>
  )
}
